image: python:3.7.3

cache:
  paths:
    - venv/

test:
  tags:
    - test
  script:
    - python3 -m venv venv/
    - source venv/bin/activate
    - pip install -r requirements.txt
    - cd app/
    - python manage.py collectstatic
    - cd ..
    - make test
